<?php 
// foreach($variants[0] as $key => $value){
//     echo $key, "=>", $value, "<br>";
// }
// die;
// echo "<pre>";
// print_r($data);
// die;
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- <script src="jquery-3.6.0.min.js"></script> -->


</head>


<body>
    
<form method="POST" action="">
    <div class="form-group">
        <label for="exampleInputEmail1">Customer Name</label>
        <input type="text" class="form-control" name="name" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Quantity</label>
        <input type="text" name="quantity" class="form-control" id="exampleInputPassword1" >
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1"></label>
        <input type="hidden" name="date" value="<?php echo date("Y-M-D") ?>" class="form-control" id="exampleInputPassword1" >
    </div>
    <div class="dropdown">
    <label for="product_name">Select Product: </label>
        <select class="product_name form-control" name="product_name" id="product_name">
            
            <option value="0">Choose a Product:</option>
            <?php foreach ($data as $k=>$i) { ?>
                <option class='product' value="<?php echo $i['_id']; ?>"><?php echo $i['category']; ?></option>
            <?php } ?>
        </select>
    </div>
    <div class="dropdown">
    <label for="product_name">Select Variants: </label>
        <select class="product_name form-control" name="variation" id="variation_name">
            </select>
        </div>
        
        <button type="submit" name="submit" class="btn btn-primary">Submit</button>
    </form>
    
    
    
    
    
    
    
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
          
    <script src="../../public/js/script.js">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>

</html>


