<?php
?>


<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
<div class="container m-5">
    <div class="row">
        <div class="dropdown col-4">
                <select class="product_status form-control "  name="product_name" id="">
                    
                    <option value="0">Choose a day:</option>
                    <option class='product' value="Today">Today</option>
                    <option class='product' value="Week">This Week</option>
                    <option class='product' value="Month">This Month</option>
                </select>
        </div>
        <div class="col-4">
        <span>
        <form method="POST" action="">    
            From <input type="Number" name="from" placeholder="Y-M-D">  <br> &nbsp To <input type="Number" name="to" placeholder="Y-M-D">
        </form>
    </span>
        </div>
    </div>
</div>

  <table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Quantity</th>
      <th scope="col">variation</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <?php 
 foreach($order as $key => $value){

    ?>
    <tr>
      <th scope="row">1</th>
      <input type="hidden" name="order_id" value="<?php echo $value->_id ?>">
      <td><?php echo $value->name; ?></td>
      <td><?php echo $value->quantity; ?></td>
      <td><?php echo $value->variation; ?></td>
      <td>
          <div class="dropdown">
              
              <input type="hidden" name="order_id" id="order_id" value="<?php echo $value->_id ?>">
              <select class="product_status form-control " data-id=<?php echo $value->_id ?> name="product_name" id="">
                  
                  <option value="0">Choose a Product:</option>
                    <option class='product' value="Paid">Paid</option>
                    <option class='product' value="Pending">Pending</option>
                    <option class='product' value="Approved">Approved</option>
              </select>
        </div>
 </td>
    </tr>
    <?php 
 }
 ?>
  </tbody>
</table>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


<!-- ------------------------------------------------------------------------------------------------------------------------------ -->
<script>
$(document).ready(function () {
    console.log("h");
    $("body").on("change",".product_status", function () {
    console.log("hhhh");
    let id = $(this).data('id');
    let val = $(this).val();
    // console.log(val);

    
    console.log(id);
        $.ajax({
        url: "http://localhost:8080/login/updateProductstatus",
        data: {
            "id": id,
            "val":val
        },
        method: "POST",
        //   dataType: "JSON"

        }).done(function (data) {
            console.log(data);
            

        });
    });
})
</script>
<!-- ------------------------------------------------------------------------------------------------------------------ -->
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>