<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
<div class="container mt-5">
    <form method="POST" action="">
    
        <!-- Email input -->
        <div class="form-outline mb-4">
            <input type="text" name="product_title" id="form2Example1" class="form-control" />
            <label class="form-label" for="form2Example1">Product Tilte</label>
        </div>

        <!-- Discription input -->
        <div class="form-outline mb-4">
            <input type="text" name="product_detail" id="form2Example2" class="form-control" />
            <label class="form-label" for="form2Example2">Discription</label>
        </div>
        <!-- Price input -->

        <div class="form-outline mb-4">
            <input type="text" name="price"  id="form2Example2" class="form-control" />
            <label class="form-label" for="form2Example2">Price</label>
        </div>
        
        <!-- 2 column grid layout for inline styling -->
            

        <!-- Submit button -->
        <button type="submit" name="submit" class="btn btn-primary btn-block mb-4">Add Product</button>

        <!-- Register buttons -->
    
    </form>
    

    
</div>
    
    
    
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->
</body>
</html>